# Generated by Django 3.1.5 on 2021-01-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionPedidos', '0002_auto_20210110_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='direccion',
            field=models.CharField(max_length=50, verbose_name='Direccion Cliente'),
        ),
    ]
